import Header from "@/components/Header";
import "./globals.css";

export const metadata = {
  title: "Create Next Portfolio",
  description: "Generated by create next portfolio",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
